In [1]:
import numpy as np
l1=[2,3,4,5,6]
arr1=np.array(l1)
print(arr1)

[2 3 4 5 6]


In [2]:
import numpy as np
A=np.array([{10,11,12,13,14},{21,22,23,24}])
print(A)

[{10, 11, 12, 13, 14} {24, 21, 22, 23}]


In [3]:
import numpy as np
arr = np.empty([3,2], dtype=int)
print(arr)

[[0 0]
 [0 0]
 [0 0]]


In [4]:
import numpy as np
arr1=np.zeros(5)
print(arr1)

[0. 0. 0. 0. 0.]


In [5]:
import numpy as np
arr1=np.ones(5)
print(arr1)

[1. 1. 1. 1. 1.]


In [6]:
import numpy as np
arr1 = np.arange(4,20,3)
print(arr1)

[ 4  7 10 13 16 19]


In [7]:
import numpy as np
A = np.array([1,2,3,4,5,6])
B = np.reshape(A,(2,3))
print(B)

[[1 2 3]
 [4 5 6]]


In [8]:
import numpy as np
data = np.array([5,2,7,3,9])
print(data[:])
print(data[1:3])
print(data[:2])
print(data[-2:])

[5 2 7 3 9]
[2 7]
[5 2]
[3 9]


In [9]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a[1:2,0:4]
print('b',b)
b=a[1:2,1:2]
print('b',b)
b=a[:2,0:2]
print('b',b)
b=a[:2,1:3]
print('b',b)
b=a[1:3,2:4]
print('b',b)

b [[5 6 7 8]]
b [[6]]
b [[1 2]
 [5 6]]
b [[2 3]
 [6 7]]
b [[ 7  8]
 [11 12]]


In [10]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = a[0:2,1:3]
print(b)
b[0,0] = 20
print(b)
print(a)
      

[[2 3]
 [6 7]]
[[20  3]
 [ 6  7]]
[[ 1 20  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
